### ISSUE TITLE
Latest version errors out

### ISSUE THREAD

**Issue by findjigar** [silverAndroid/drivetest-ca-availabilities#33]
**Describe the bug**
Getting below error when trying to execute the latest binary
```
ERROR (4019 on MacBook): Error: Failed to launch the browser process!


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at onClose (/snapshot/drivetest-ca-availabilities/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:193:20)
    at Interface.<anonymous> (/snapshot/drivetest-ca-availabilities/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:183:68)
    at Interface.emit (events.js:387:35)
    at Interface.close (readline.js:451:8)
    at Socket.onend (readline.js:224:10)
    at Socket.emit (events.js:387:35)
    at endReadableNT (internal/streams/readable.js:1317:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
```

**To Reproduce**

1. Downloaded latest binary from release notes
2. Did `chmod a+x` to make the binary executable
3. Gave Apple security permission to run the binary anyway
4. Then ran this command `./drivetest-availabilities-macos -r 60 -l “xx.xxxxxx, -xx.xxxxxx” --licenseType G --email xx@gmail.com --licenseNumber Bxxxx-xxxxx-xxxxxx --licenseExpiry “xxxx/xx/xx”`
5. And getting above error

**Expected behavior**
Get some kind of valid output

**Desktop (please complete the following information):**

- macOS 11.3.1

**Comment by silverAndroid** [comment]
@findjigar if you delete the `.local-chromium` folder and run the binary again, what happens?

**Comment by findjigar** [comment]
@silverAndroid Same as before
```
Downloading compatible version of Chrome - 111.1 Mb [====================] 100% 0.0s
INFO (10414 on MacBook): Checking for updates...
INFO (10414 on MacBook): No new updates found, current version 1.5.0
INFO (10414 on MacBook): If you appreciate my work, feel free to buy me a ☕️ (coffee) here 😊: https://www.buymeacoffee.com/rushilperera
ERROR (10414 on MacBook-Pro.local): Error: Failed to launch the browser process!


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at onClose (/snapshot/drivetest-ca-availabilities/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:193:20)
    at Interface.<anonymous> (/snapshot/drivetest-ca-availabilities/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:183:68)
    at Interface.emit (events.js:387:35)
    at Interface.close (readline.js:451:8)
    at Socket.onend (readline.js:224:10)
    at Socket.emit (events.js:387:35)
    at endReadableNT (internal/streams/readable.js:1317:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
```
