### ISSUE TITLE
It gives a "Passed function is not well-serializable!" error

### ISSUE THREAD

**Issue by nisarg89** [silverAndroid/drivetest-ca-availabilities#6]
[drivetest-2021-05-01_13-20-45.log](https://github.com/silverAndroid/drivetest-ca-availabilities/files/6410023/drivetest-2021-05-01_13-20-45.log)

**Comment by nisarg89** [comment]
More details from the shell:

ERROR (17400 on DESKTOP-FA26792): Error: Passed function is not well-serializable!
    at ExecutionContext._evaluateInternal (C:\snapshot\drivetest-ca-availabilities\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:196:23)
    at ExecutionContext.evaluate (C:\snapshot\drivetest-ca-availabilities\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:107:27)
    at DOMWorld.evaluate (C:\snapshot\drivetest-ca-availabilities\node_modules\puppeteer\lib\cjs\puppeteer\common\DOMWorld.js:91:24)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

**Comment by silverAndroid** [comment]
Dang, I thought I had fixed this already. I'll take a look at this
